import { TokenList } from "../types/token";

const tokenList: TokenList = {
  destination: "from",
  from: {
    id: 2,
    name: "NULS",
    address: "NULSd6Hgmqgq924JD5aukswyrqrg6xjpTzH5w",
    symbol: "NULS",
    decimals: 8,
    chainId: 1,
    logoURI: "/tokens/nuls.png",
    type: "Nuls",
    chain: 1,
    asset: 1,
    tags: [""],
  },
  to: {
    id: 1,
    name: "Nulswap",
    address: "NULSd6HgrzcXdTuGvRF9DmkxoXM8XNmXZs95d",
    symbol: "NSWAP",
    decimals: 8,
    chainId: 1,
    logoURI: "/tokens/nswap-circ.png",
    type: "Token",
    chain: 0,
    asset: 0,
    tags: [""],
  },

  initial: {
    id: 100,
    name: "",
    address: "",
    symbol: "",
    tags: [""],
    decimals: 8,
    chainId: 0,
    logoURI: "/tokens/nswap.png",
    type: "Token",
    chain: 0,
    asset: 0,
  },

  tokens: [
    {
      id: 2,
      name: "NULS",
      address: "NULSd6Hgmqgq924JD5aukswyrqrg6xjpTzH5w",
      symbol: "NULS",
      decimals: 8,
      chainId: 1,
      logoURI: "/tokens/nuls.png",
      type: "Nuls",
      chain: 1,
      asset: 1,
      tags: [""],
    },
    {
      id: 5701666712059904,
      name: "Nulswap",
      address: "NULSd6HgrzcXdTuGvRF9DmkxoXM8XNmXZs95d",
      symbol: "NSWAP",
      tags: ["roll"],
      decimals: 8,
      chainId: 1,
      logoURI: "/tokens/nswap-circ.png",
      type: "Token",
      chain: 0,
      asset: 0,
    },

    {
      id: 1004273878,
      name: "aiNULS",
      address: "NNULSd6HgvVgJVUdLEGgHK3ziP2riBkZaNbtPX",
      symbol: "aiNULS",
      decimals: 8,
      chainId: 1,
      logoURI: "/tokens/ainuls.png",
      type: "Token",
      chain: 0,
      asset: 0,
      tags: [""],
    },
    {
      id: 57016667120259904,
      name: "WTF",
      address: "NULSd6Hgr7kEY9dEJVEpjsWAgmGRqBiMe9vL7",
      symbol: "WTF",
      tags: ["roll"],
      decimals: 8,
      chainId: 1,
      logoURI: "/tokens/wtf-circ.svg",
      type: "Token",
      chain: 0,
      asset: 0,
    },

    {
      id: 5701699920,
      name: "BULS",
      address: "NULSd6HgvhaiirRcbg3QY7GWSU6RSFGaVovme",
      symbol: "BULS",
      tags: ["roll"],
      decimals: 8,
      chainId: 1,
      logoURI: "/tokens/buls.png",
      type: "Token",
      chain: 0,
      asset: 0,
    },
    
    {
      id: 100000,
      name: "Earhart",
      address: "NULSd6HgvzxmmEa65N2L9MfPXX9e129ayQPEz",
      symbol: "EHT",
      decimals: 8,
      chainId: 1,
      logoURI: "/tokens/earhart.png",
      type: "Token",
      chain: 0,
      asset: 0,
      tags: [""],
    },
    {
      id: 56656743262,
      name: "USDTN",
      address: "NULSd6HgtbwRaxcPtvYnzWjCprnxudVErzbty",
      symbol: "USDTN",
      tags: ["roll"],
      decimals: 18,
      chainId: 9,
      logoURI: "/tokens/USDTN.png",
      type: "Multi",
      chain: 9,
      asset: 220,
    },

    {
      id: 5701666712059920,
      name: "Nabox",
      address: "NULSd6Hgv3Y49CHapt5qL4pCiEX8x3ZHrh6ie",
      symbol: "Nabox",
      tags: ["roll"],
      decimals: 18,
      chainId: 1,
      logoURI: "/tokens/nabox.png",
      type: "Token",
      chain: 0,
      asset: 0,
    },
    {
      id: 100001,
      name: "Niftyfuse",
      address: "NULSd6HgyvAVKLFRNWcWrrgHFGUtYRe3Ev49Z",
      symbol: "FUSE",
      decimals: 8,
      chainId: 1,
      logoURI: "/tokens/niftyfuse.jfif",
      type: "Token",
      chain: 0,
      asset: 0,
      tags: [""],
    },

    {
      id: 100004,
      name: "GGDAPP (NRC20)",
      address: "NULSd6HgpbLVcH8uZAkpC6TabyjsYD26X7EyF",
      symbol: "GGTK",
      decimals: 8,
      chainId: 1,
      logoURI:
        "https://assets.coingecko.com/coins/images/13666/small/ggtk.png?1629348879",
      type: "Token",
      chain: 0,
      asset: 0,
      tags: [""],
    },

    {
      id: 566567340973824416210200,
      name: "BUSD (BSC)",
      address: "NULSd6HgqbD7DX9uYsjGA5pfRx7SKKy34VjGF",
      symbol: "BUSD",
      tags: ["roll"],
      decimals: 18,
      chainId: 9,
      logoURI:
        "https://content-api.changenow.io/uploads/busdbsc_321c390762.svg",
      type: "Multi",
      chain: 9,
      asset: 30,
    },
    {
      id: 56656743263409738244162,
      name: "NVT",
      address: "NULSd6HgmiVXj8QfAex2XxxsCbKdPaWQ2NwdH",
      symbol: "NVT",
      tags: ["roll"],
      decimals: 8,
      chainId: 9,
      logoURI: "/tokens/nerve.png",
      type: "Multi",
      chain: 9,
      asset: 1,
    },
  ],
};

export default tokenList;
